// <auto-generated />
using System;
using CaseInvestigationManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaseInvestigationManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325134027_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaseInvestigationManagementSystem.Models.AuditTrailModel", b =>
                {
                    b.Property<int>("audit_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("audit_id"));

                    b.Property<string>("action")
                        .HasColumnType("text");

                    b.Property<int>("case_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("new_status")
                        .HasColumnType("text");

                    b.Property<string>("old_status")
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("audit_id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("CaseInvestigationManagementSystem.Models.CaseModel", b =>
                {
                    b.Property<int>("case_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("case_id"));

                    b.Property<int?>("assigned_to")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_at_formatted")
                        .HasColumnType("text");

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("investigator_name")
                        .HasColumnType("text");

                    b.Property<string>("priority")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("case_id");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("CaseInvestigationManagementSystem.Models.CommentModel", b =>
                {
                    b.Property<int>("comment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("comment_id"));

                    b.Property<int>("case_id")
                        .HasColumnType("integer");

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.HasKey("comment_id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CaseInvestigationManagementSystem.Models.DocumentModel", b =>
                {
                    b.Property<int>("doc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("doc_id"));

                    b.Property<int>("case_id")
                        .HasColumnType("integer");

                    b.Property<string>("file_name")
                        .HasColumnType("text");

                    b.Property<string>("file_path")
                        .HasColumnType("text");

                    b.Property<DateTime>("uploaded_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("uploaded_by")
                        .HasColumnType("integer");

                    b.HasKey("doc_id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CaseInvestigationManagementSystem.Models.UserModel", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("password_hash")
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
